#!/usr/bin/env node
// Compiles wasm/dsp.c to WebAssembly with clang (wasm32 target, no libc) and
// embeds the binary as base64 in src/audio/wasm/dspWasm.ts so the app builds
// without a C toolchain.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'wasm/dsp.c');
const outDir = resolve(root, 'wasm/build');
const wasmOut = resolve(outDir, 'dsp.wasm');
const tsOut = resolve(root, 'src/audio/wasm/dspWasm.ts');

mkdirSync(outDir, { recursive: true });

const clang = process.env.CLANG || 'clang';
const args = [
  '--target=wasm32',
  '-O3',
  '-ffreestanding',
  '-nostdlib',
  '-mbulk-memory',
  '-fno-exceptions',
  '-Wall',
  '-Wextra',
  '-Wno-unused-parameter',
  '-Wl,--no-entry',
  '-Wl,--export-dynamic',
  '-Wl,--allow-undefined',
  '-Wl,--initial-memory=2097152',
  '-Wl,--max-memory=2147483648',
  '-Wl,--strip-all',
  '-o',
  wasmOut,
  src,
];

console.log(`${clang} ${args.join(' ')}`);
execFileSync(clang, args, { stdio: 'inherit' });

const bytes = readFileSync(wasmOut);
const b64 = bytes.toString('base64');
const banner = `// Generated by scripts/build-wasm.mjs from wasm/dsp.c. Do not edit.\n`;
writeFileSync(
  tsOut,
  `${banner}// ${bytes.length} bytes\nexport const DSP_WASM_BASE64 =\n  '${b64}';\n`,
);
console.log(`wrote ${tsOut} (${bytes.length} bytes wasm)`);
